### PR TITLE
Incorrect URL for category filter fixes

### LINKED ISSUE #149: Incorrect URL for category filter
Issue Brief
--
What is the purpose of this issue? Explain the background context.

Environment
--
* PHP Version: 7.3
* Magento Version: 2.3.6-p2
* Tweakwise Version: 3.3.1
* Tweakwise Export Version: 2.1.0
* Magento Deploy Mode: both
* Third party modules: very much ;)

Steps to reproduce
--
Using the default category filter in Tweakwise returns incorrect URL slugs.

Actual result
--
Example: /nl/nl/collecting-waste/waste-bins-paper-bins/waste-separation
Expected: /nl/afval-verzamelen/afvalemmers-prullenbakken/afvalscheiding/

Expected result
--
The correct URL slug without duplicate store codes and in the correct language.

### PR DESCRIPTION
**Pull request by Hnto**
- Add storeId if available in `StrategyHelper::getCategoryFromItem`. If no store is found, use `null`;
- Remove double store code from url in `PathSlugStrategy::getCategoryFilterSelectUrl`
- Remove double store code from url in `QueryParameterStrategy::getCategoryFilterSelectUrl`

Fixes #149

### CODE REVIEW

File: Model/Catalog/Layer/Url/Strategy/PathSlugStrategy.php [hunk 1]
```diff
@@ -507,18 +507,26 @@ public function getCategoryFilterSelectUrl(
...
+        $url = $this->magentoUrl->getDirectUrl(
             sprintf(
                 '%s/%s',
                 trim($categoryUrlPath, '/'),
                 ltrim($filterSlugPath, '/')
             )
         );
+
+        /*
+         We explode the url by using a backslash as separator and then filter the values
```
Comment (stijnbernards) [inline Model/Catalog/Layer/Url/Strategy/PathSlugStrategy.php]: But why do we explode the url? ;)

The code already explains what we're doing, the comment should explain why we're doing it.

Comment (Hnto) [reply Model/Catalog/Layer/Url/Strategy/PathSlugStrategy.php]: Agreed :)
