### PR TITLE
Wrong upsell/crossell template

### LINKED ISSUE #258: Wrong crosssell and upsell templates of second Tweakwise environment
Issue Brief
--
We have a Magento 2 environment that has **multiple** store views. Each store view uses their own Tweakwise Environment and therefor a different **Catalog / Tweakwise / General / Authentication Key** in the admin. 

When we go to the second store view level in the admin, then we see the **different authentication key**. But when we scroll down to **Catalog / Tweakwise / Default Crosssell template and Default Upsell template** then we see the templates of our **other storeview**.

So we believe the **wrong authentication key** is used when **loading** these templates. Possibly the one that's set on the default level.

Environment
--
* PHP Version: (5.6|7.0|7.1)
* Magento Version: 2.4.2-p2
* Tweakwise Version: v3.3.8
* Tweakwise Export Version: v2.1.0
* Magento Deploy Mode: production

Steps to reproduce
--
1. Have two store views in Magento 2 en two environments in Tweakwise.
2. Set default and first store view Tweakwise authentication key to key number 1
3. Set second store view Tweakwise authentication to key number 2
4. Attempt to select crosssell and upsell templates under Catalog / Tweakwise / Default Crosssell template and Default Upsell template

Actual result
--
On default and both store view levels the selects show only the templates of environment number 1.

Expected result
--
On the default and first store view level, we expect to see templates of environment number 1.
On the second store view level, we expect to see templates of environment number 2.

### PR DESCRIPTION
**Pull request by ahuininga-orisha**
Fixes #258 

This gets the storeId from the selected scope from the (admin) requests and add that to the function fetching the config value.

### CODE REVIEW

File: Model/Config.php [hunk 1]
```diff
@@ -73,15 +76,25 @@ class Config
...
+     */
+    protected $storeId = null;
+
     /**
      * Export constructor.
      *
      * @param ScopeConfigInterface $config
      */
-    public function __construct(ScopeConfigInterface $config, Json $jsonSerializer)
+    public function __construct(ScopeConfigInterface $config, Json $jsonSerializer, Http $request, State $state)
```
Comment (Hnto) [inline Model/Config.php]: Please use the `Magento\Framework\App\RequestInterface` for this

File: Model/Config.php [hunk 2]
```diff
@@ -73,15 +76,25 @@ class Config
...
     {
         $this->config = $config;
         $this->jsonSerializer = $jsonSerializer;
+
+        //only do this if its an admin request, to prevent setting the store id in the url in the frontend
+        if ($state->getAreaCode() == Area::AREA_ADMINHTML) {
```
Comment (Hnto) [inline Model/Config.php]: Strict type checking

**Review by Hnto — CHANGES_REQUESTED** [review]
