### PR TITLE
Fix grouped/bundeled prices in autocomplete

### LINKED ISSUE #24: Grouped and bundle products have zero price in a quick search popup
### Expected behaviour
Grouped and bundle products have a correct price in a quick search popup

### Actual behaviour
Grouped and bundle products have zero price

### Why?
There are two issues:

`\Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem::toArray`

```php
/**
 * @return array
 */
public function toArray(): array
{
    $product = $this->product;
    $price = $product->getPriceInfo();
    $image = $this->getImage();

    return [
        'title' => $this->getTitle(),
        'url' => $product->getProductUrl(),
        'image' => $image->getImageUrl(),
        'price' => (float) $price->getPrice('regular_price')->getValue(),
        'final_price' => (float) $price->getPrice('final_price')->getValue(),
        'type' => 'product',
        'row_class' => 'qs-option-product',
    ];
}
```

This method above cannot be used for all product types such as bundle and grouped ones as they have different pricing calculations strategies;
Actually, these product items are populated in the next method call

`\Emico\Tweakwise\Model\Autocomplete\DataProviderHelper::getProductItems`

Via $productCollection - but, this approach (using collections) uses price index tables to speed up the request processing and not to calculate all the prices during the request which is common. And, this price index table is populated by a default magento price indexer. And that's what happens during the grouped products price generation (it's a default magento code)

`\Magento\GroupedProduct\Model\ResourceModel\Product\Indexer\Price\Grouped::prepareGroupedProductPriceDataSelect`
```php
...

$select->join(
    ['i' => $this->getMainTable($dimensions)],
    'i.entity_id = l.linked_product_id',
    [
        'tax_class_id' => $taxClassId,
        'price' => new \Zend_Db_Expr('NULL'),
        'final_price' => new \Zend_Db_Expr('NULL'),
        'min_price' => new \Zend_Db_Expr('MIN(' . $minCheckSql . ')'),
        'max_price' => new \Zend_Db_Expr('MAX(' . $maxCheckSql . ')'),
        'tier_price' => new \Zend_Db_Expr('NULL'),
    ]
);
...
```

As we can see a price and a final_price are set to NULL in the core Magento code.
And if you run this SQL query you'll see empty price & final_price columns
*15079 is an example id of one of some grouped products

```sql
SELECT * FROM catalog_product_index_price_replica WHERE entity_id = 15079 
```

As for the bundle products the way of getting a price and a regular price should be also different, something like this
*We should be cautious of using this functions as they do some extra SQL queries per a product

```php
$price->getPrice('final_price')->getMinimalPrice()->getValue()
$price->getPrice('regular_price')->getMinimalPrice()->getValue()
```

So the source code should be reworked according to Magento price model flows

`\Emico\Tweakwise\Model\Autocomplete\DataProvider\ProductItem::toArray`

### Versions

- Magento 2.4.3-p1
- Tweakwise 4.2.0
- Tweakwise Hyvä 1.0.0

### PR DESCRIPTION
**Pull request by ahuininga-orisha**
Fixes https://github.com/EmicoEcommerce/Magento2TweakwiseHyva/issues/24

Grouped/bundled prices in the autocomplete dropdown are not correct. This fix uses the price from tweakwise to show in the autocomplete dropdown.

### CODE REVIEW

File: Model/Autocomplete/DataProvider/ProductItem.php [hunk 1]
```diff
@@ -75,15 +75,24 @@ public function getTitle(): string
...
     {
         $product = $this->product;
-        $price = $product->getPriceInfo();
+        $priceInfo = $product->getPriceInfo();
+        $productType = $product->getTypeId();
         $image = $this->getImage();
 
+        $price = (float) $priceInfo->getPrice('regular_price')->getValue();
+
+        if ($productType == 'grouped' || $productType == 'bundle') {
```
Comment (Hnto) [inline Model/Autocomplete/DataProvider/ProductItem.php]: Please use the respective type codes for this. For instance, 'grouped' can be found in `Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE`

File: Model/Autocomplete/DataProvider/ProductItem.php [hunk 2]
```diff
@@ -75,15 +75,24 @@ public function getTitle(): string
...
+            $price = (float) $product->getData('tweakwise_price');
+        }
+
+        $finalPrice = (float) $priceInfo->getPrice('final_price')->getValue();
```
Comment (Hnto) [inline Model/Autocomplete/DataProvider/ProductItem.php]: You don't need the $finalPrice variable for this right? You can just add the code inline in 'final_price' =>

**Review by Hnto — CHANGES_REQUESTED** [review]

**Comment by epolish** [comment]
Hello, guys! Thanks a lot for that fix!
I've found another issue in 
`vendor/emico/tweakwise/Model/Autocomplete/DataProviderHelper.php::getProductItems() line 147`
The foreach loop should be like this

```
foreach ($response->getProductData() as $item) {
    $product = $productCollection->getItemById($item['id']);

     if (!$product) {
        continue;
    }

    $product->setData('tweakwise_price', $item['tweakwise_price']);

    $result[] = $this->productItemFactory->create(['product' => $product]);
}
```

Because a product can be null
```
$product = $productCollection->getItemById($item['id']);
$product->setData('tweakwise_price', $item['tweakwise_price']);
```
